name: CI

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: [24, 22, 20]
        os: [windows-latest, macos-latest, ubuntu-latest]
        arch: [x64]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.arch }}
      - name: Install
        run: npm install
        env:
          TARGET_ARCH: ${{ matrix.arch }}
      - name: Test
        run: npm test
